name: Build and Deploy Angular App to GitHub Pages

on:
  push:
    branches:
      - master  # or master, depending on your default branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Set the Node.js version (adjust as needed)

    - name: Install dependencies
      run: npm install

    - name: Build the Angular project
      run: npm run build --if-present --prod

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages  # The branch to deploy to (this is usually 'gh-pages')
        folder: dist/portfolio  # Replace with your Angular project's build output folder
        token: ${{ secrets.GH_TOKEN }}  # GitHub automatically provides this token

